apiVersion: apps/v1
kind: Deployment # pod 여러개
metadata:
  name: mariadb-user-deployment
spec: # 어떻게 만들지에 대한 내용
  replicas: 1 # pod 몇 개 만들래
  selector:
    matchLabels:
      app: mariadb-user # 쿠버네티스 안에서 변수명
  template:
    metadata:
      labels:
        app: mariadb-user # 서비스에서 찾는 변수명
    spec: # pod 하나하나에 대한 내용
      containers:
        - name: mariadb-user
          image: mariadb # dockerhub에 있는 image
          ports:
            - containerPort: 3306
          env: # 환경설정
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef: 
                  name: mariadb-secret
                  key: password
          volumeMounts:
            - name: mariadb-initdb-config-user
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mariadb-initdb-config-user
          configMap:
            name: mariadb-initdb-config-user

--- # 환경을 두 개 지정할 때 쓰는 구분자

apiVersion: v1
kind: Service
metadata:
  name: mariadb-user
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30306
  selector:
    app: mariadb-user