server:
  port: 20001

spring:
  application:
    name: order-service
  datasource:
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.0.68:30307/msa?serverTimezone=Asia/Seoul
  output:
    ansi:
      enabled: always

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    show-sql: true
    open-in-view: false

logging:
  level:
    org.springframework.web: DEBUG    # HTTP 요청 관련 로그 (Actuator HTTP 엔드포인트) 이거 해야 다 나옴...
  pattern:
    correlation: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
#  pattern:
#    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"  # 파일 로그 패턴

# refresh 가 되는 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0 # 모든 요청을 추적 (0.1로 설정하면 10%만 추적)
    zipkin:
      enabled: true
      endpoint: http://192.168.0.68:9411/api/v2/spans

gateway:
  ip: 127.0.0.1

catalog-service-url: http://localhost:20002
user-service-url: http://localhost:20000