apiVersion: apps/v1
kind: Deployment # pod 여러개
metadata:
  name: catalog-service-deployment
spec: # 어떻게 만들지에 대한 내용
  replicas: 1 # 몇개의 pod 만들래?
  selector:
    matchLabels:
      app: catalog-service # 쿠버네티스 안에서 변수명
  template:
    metadata:
      labels:
        app: catalog-service # 서비스에서 찾는 변수명
    spec: # pod 하나하나에 대한 내용
      containers:
        - name: catalog-service
          image: seungyongi/catalog-service:msa.k8.03 # dockerhub 에 있는 image
          ports:
            - containerPort: 40005 #default
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: msa-k8s-configmap
                  key: spring-datasource-url-catalog
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: msa-k8s-configmap
                  key: spring-datasource-username
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: msa-k8s-configmap
                  key: catalog-service-port
            - name: FIRST_SERVICE_URL
              value: first-service:40001
            - name: ORDER_SERVICE_URL
              value: order-service:40004
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: msa-k8s-configmap
                  key: spring-kafka-bootstrap-servers

---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  type: LoadBalancer
  ports:
    - port: 40005
      targetPort: 40005
  selector:
    app: catalog-service