apiVersion: apps/v1
kind: Deployment # pod 여러개
metadata:
  name: order-service-deployment
spec: # 어떻게 만들지에 대한 내용
  replicas: 1 # pod 몇 개 만들래
  selector:
    matchLabels:
      app: order-service # 쿠버네티스 안에서 변수명
  template:
    metadata:
      labels:
        app: order-service # 서비스에서 찾는 변수명
    spec: # pod 하나하나에 대한 내용
      containers:
        - name: order-service
          image: seungyongi/order-service:msa.k8.01 # dockerhub에 있는 image
          ports:
            - containerPort: 40004
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: msa-k8s-configmap
                  key: spring-datasource-url-order
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: msa-k8s-configmap
                  key: spring-datasource-username
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: msa-k8s-configmap
                  key: order-service-port
            - name: USER_SERVICE_URL
              value: user-service:40003
            - name: CATALOG_SERVICE_URL
              value: catalog-service:40005


--- # 환경을 두 개 지정할 때 쓰는 구분자

apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: LoadBalancer
  ports:
    - port: 40004
      targetPort: 40004
  selector:
    app: order-service